language: ruby
rvm:
- 2.5
sudo: required
services:
  - docker
install: bundle install
sudo: false

script:
- docker run --rm -it --volume `pwd`:/opt/app --workdir /opt/app node:carbon-alpine /bin/sh -c "npm install && npm run build" && bundle exec jekyll build
- docker run --name=site -d --volume `pwd`/_site:/var/www node:carbon-alpine /bin/sh -c "npm i serve && npx serve /var/www"
- docker run --rm -it --link site --volume `pwd`:/opt/app --workdir /opt/app -e TEST_SERVER_URL=http://site:5000 p2pu/puppeteer-docker /bin/sh -c "npm install --only=dev && npm run test"

after_success:
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then echo "Deployments are only done for branches. "; exit 0; fi
- if [[ "$TRAVIS_BRANCH" != "release"]] && [["$TRAVIS_BRANCH" != "master"]]; then echo "Only release and master branches are deployed"; exit 0; fi
- echo "Deploying commit $TRAVIS_COMMIT"
- bundle exec s3_website cfg apply --headless
- bundle exec s3_website push

env:
  global:
  - secure: aCvpyjljg3FDHvwgNKHzGLS4m9JKEZ2fBdTc2SO+iVEb7q/hvmOCb9M3xyhzug0dIXjCnrjCsAF3MnQ/BQLQVjCnL9+2IH0rxRcx7fIAAsuZ6FCgL/ohzPGZVK2qqdXhujMDu3t3O+auA8T3vN3siG1ophXKHcqe9/spve/WmwU=
  - secure: MD3BKhnUEnE/JMKkwrycFJX6YI3QyYwpf9C14qXKh0HJ/3m0Fuz2e2KzRbD8kK7Qh4UKgJPp/1RUcnf6mTsMoZpacWYt1sv/5tiiqmBuK6UeYVd8oczhkD7swuj+xqr2i4MZPMoo3cFEQaXnvNgkVkEa4M6P4vHQVls566lZCy0=
