language: ruby
rvm:
- 2.5
sudo: false
services:
- docker
install: bundle install
script: ./script/cibuild.sh
after_success:
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then echo "Deployments are only done
  for branches. "; exit 0; fi
- if [[ "$TRAVIS_BRANCH" != "release" ]] && [[ "$TRAVIS_BRANCH" != "master" ]]; then
  echo "Only release and master branches are deployed"; exit 0; fi
- echo "Deploying commit $TRAVIS_COMMIT"
- bundle exec s3_website cfg apply --headless
- bundle exec s3_website push
env:
  global:
  - secure: aCvpyjljg3FDHvwgNKHzGLS4m9JKEZ2fBdTc2SO+iVEb7q/hvmOCb9M3xyhzug0dIXjCnrjCsAF3MnQ/BQLQVjCnL9+2IH0rxRcx7fIAAsuZ6FCgL/ohzPGZVK2qqdXhujMDu3t3O+auA8T3vN3siG1ophXKHcqe9/spve/WmwU=
  - secure: MD3BKhnUEnE/JMKkwrycFJX6YI3QyYwpf9C14qXKh0HJ/3m0Fuz2e2KzRbD8kK7Qh4UKgJPp/1RUcnf6mTsMoZpacWYt1sv/5tiiqmBuK6UeYVd8oczhkD7swuj+xqr2i4MZPMoo3cFEQaXnvNgkVkEa4M6P4vHQVls566lZCy0=
  - secure: Zbqi9ozdPCznyM54srR2+iv6zVWX0Q2CY/uns0kw47nzP9amV3Gi22LKJjFCdKNn8lATZebXR3gz4C4H0xGGWSuF4zEp+UFcNjuGwqmwkvu3+4On19c3MWFsgjPNsa6zrp+PozZ98VqEgc6qHBSNlwNgO/YFBJBHfgIZCN0usYw=
