language: ruby
rvm:
- 2.5
branches:
  only:
  - gh-pages
  - release
sudo: required
services:
  - docker
install: bundle install
sudo: false

script:
- docker run --rm -it --volume `pwd`:/opt/app --workdir /opt/app node:boron-alpine /bin/sh -c "npm install && npm run build" && bundle exec jekyll build

after_success:
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then echo "Deployments are only done for branches. "; exit 0; fi
- echo "Deploying commit $TRAVIS_COMMIT"
- bundle exec s3_website cfg apply --headless
- bundle exec s3_website push

env:
  global:
  - secure: aCvpyjljg3FDHvwgNKHzGLS4m9JKEZ2fBdTc2SO+iVEb7q/hvmOCb9M3xyhzug0dIXjCnrjCsAF3MnQ/BQLQVjCnL9+2IH0rxRcx7fIAAsuZ6FCgL/ohzPGZVK2qqdXhujMDu3t3O+auA8T3vN3siG1ophXKHcqe9/spve/WmwU=
  - secure: MD3BKhnUEnE/JMKkwrycFJX6YI3QyYwpf9C14qXKh0HJ/3m0Fuz2e2KzRbD8kK7Qh4UKgJPp/1RUcnf6mTsMoZpacWYt1sv/5tiiqmBuK6UeYVd8oczhkD7swuj+xqr2i4MZPMoo3cFEQaXnvNgkVkEa4M6P4vHQVls566lZCy0=
