# Site settings
title: P2PU
email: admin@p2pu.org
description: "Grassroots community supporting equitable, empowering peer learning in public spaces worldwide. Learning for the people, by the people!"
baseurl:
url: "https://www.p2pu.org"
languages: ['en']
default_language: 'en'
default_image_path: /assets/images/p2pu-ogimg-default.jpg

# Build settings
markdown: CommonMark
permalink: pretty

collections:
  teams:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "teams"
    values:
      layout: "team"
      permalink: "/:title/"

#SASS settings
sass:
  load_paths:
    - _sass
    - node_modules
  style: :compressed

env: prod

mapbox_access_token: pk.eyJ1Ijoic2hhcm9uLW5vbWFkaWMtbGFicyIsImEiOiJjanJtY2xuc2MwaG95NDNtbmUwa3o5bjRpIn0.fZpeaYNgU3Nh5NAcNLW5BQ
default_base_api_endpoint: 'https://learningcircles.p2pu.org'

exclude:
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README
  - s3_website.yml
  - node_modules

prose:
  media: assets/images
