# Site settings
title: P2PU
email: admin@p2pu.org
description: "Taking online courses together, in libraries, for free."
baseurl:
url: "http://p2pu.org"
languages: ['en']
default_language: 'en'

# Build settings
markdown: kramdown
permalink: pretty

#SASS settings
sass:
  load_paths:
    - _sass
    - node_modules
  style: :compressed

env: prod

mapbox_access_token: 'pk.eyJ1Ijoic2hhcm9uLW5vbWFkaWMtbGFicyIsImEiOiJjanJtY2xuc2MwaG95NDNtbmUwa3o5bjRpIn0.fZpeaYNgU3Nh5NAcNLW5BQ'
default_base_api_endpoint: 'http://localhost:8000'

exclude:
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README
  - s3_website.yml
  - node_modules

prose:
  media: assets/images
