on:
  pull_request:
    types: [closed]

jobs:
  terraform-cleanup:
    name: "Terraform"
    runs-on: ubuntu-latest
    outputs:
      s3_bucket: ${{ steps.s3_bucket.outputs.stdout }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Cleanup
        id: init
        run: terraform init --backend-config="key=tfstate/p2pu-website/${{ steps.extract_branch.outputs.branch }}"
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform apply
        id: apply
        if: github.event_name == 'pull_request'
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
